import React from 'react'

const exampleTimelineItemData =

{
  "position": 0,
  "trackName": "S.T.A.Y.",
  "description": "S.T.A.Y. by Hans Zimmer",
  "image": {
    "height": 640,
    "url": "https://i.scdn.co/image/ab67616d0000b273ac29a65e7ffcfa6f9cb0d342",
    "width": 640
  },
  "track": {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/0YC192cP3KPCRWx8zr8MfZ"
          },
          "href": "https://api.spotify.com/v1/artists/0YC192cP3KPCRWx8zr8MfZ",
          "id": "0YC192cP3KPCRWx8zr8MfZ",
          "name": "Hans Zimmer",
          "type": "artist",
          "uri": "spotify:artist:0YC192cP3KPCRWx8zr8MfZ"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/3B61kSKTxlY36cYgzvf3cP"
      },
      "href": "https://api.spotify.com/v1/albums/3B61kSKTxlY36cYgzvf3cP",
      "id": "3B61kSKTxlY36cYgzvf3cP",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273ac29a65e7ffcfa6f9cb0d342",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02ac29a65e7ffcfa6f9cb0d342",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851ac29a65e7ffcfa6f9cb0d342",
          "width": 64
        }
      ],
      "name": "Interstellar (Original Motion Picture Soundtrack) [Expanded Edition]",
      "release_date": "2014-11-18",
      "release_date_precision": "day",
      "total_tracks": 30,
      "type": "album",
      "uri": "spotify:album:3B61kSKTxlY36cYgzvf3cP"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0YC192cP3KPCRWx8zr8MfZ"
        },
        "href": "https://api.spotify.com/v1/artists/0YC192cP3KPCRWx8zr8MfZ",
        "id": "0YC192cP3KPCRWx8zr8MfZ",
        "name": "Hans Zimmer",
        "type": "artist",
        "uri": "spotify:artist:0YC192cP3KPCRWx8zr8MfZ"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW"
    ],
    "disc_number": 1,
    "duration_ms": 383513,
    "explicit": false,
    "external_ids": {
      "isrc": "USNLR1400787"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/6GUq9y0Iy5QrAuPYxTrFp2"
    },
    "href": "https://api.spotify.com/v1/tracks/6GUq9y0Iy5QrAuPYxTrFp2",
    "id": "6GUq9y0Iy5QrAuPYxTrFp2",
    "is_local": false,
    "name": "S.T.A.Y.",
    "popularity": 62,
    "preview_url": "https://p.scdn.co/mp3-preview/e06dd7ceaf2f282e7829349c27aeebec2f55e0b9?cid=b8ba6d4e39f84e1897de4f879dba11ca",
    "track_number": 15,
    "type": "track",
    "uri": "spotify:track:6GUq9y0Iy5QrAuPYxTrFp2"
  },
  "played_at": "2021-10-11T18:54:37.936Z"
}

const TimelineItem = ({ timelineItemData }) => {
  //UNCOMMENT WHEN RUNNING FIREBASE EMULATOR/LIVE
  // if(!timelineItemData) {
  //   return <p>Loading...</p>    
  // }  
  //COMMENT THIS WHEN RUNNING FIREBASE EMULATOR/LIVE
  timelineItemData = exampleTimelineItemData
  return (<div className="container">
    <p>{timelineItemData.trackName}</p>
    <style jsx>{`
    .container {
        position:relative;
      font: 15px Helvetica, Arial, sans-serif;
      background: gray;
      width 100%;
      height 120px;
      text-align: center;          
      border-radius: 5%;
    }
    .container:hover {
      filter: brightness(1.5);
    }
    .image {
        width: 100%;
        height: 100%;
        padding: 2%;        
        border-radius: 50%;
    }
  `}</style>
  </div>)
}

export default TimelineItem
