name: Deploy Preview
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Populate service account
        run: 'echo "$SERVICE_ACCOUNT" > service-account.json'
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Install Dependencies
        run: 'yarn install'
        shell: bash
      - name: ESLint
        run: 'yarn eslint'
        shell: bash
      - name: Build
        run: 'yarn build'
        shell: bash
        env:
          FIREBASE_API_KEY : ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_AUTH_DOMAIN :  ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL : ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID : ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET : ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID : ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          AUTH_REDIRECT_URL : ${{ secrets.AUTH_REDIRECT_URL }}
          SPOTIFY_CLIENT_ID : ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET : ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SITE_ADDRESS : ${{ secrets.SITE_ADDRESS }}
          NEXT_PUBLIC_MAPS_API_KEY : ${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: .next
          path: .next
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: .next
          path: .next
      - name: Install firebase-functions
        run: 'yarn add firebase-functions'
        shell: bash      
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name:  Deploy to Firebase Channel
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${GITHUB_REF##*/}
        env:
          FIREBASE_TOKEN:  ${{ secrets.FIREBASE_CI_TOKEN }}
          FIREBASE_API_KEY : ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_AUTH_DOMAIN :  ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL : ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID : ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET : ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID : ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          AUTH_REDIRECT_URL : ${{ secrets.AUTH_REDIRECT_URL }}
          SPOTIFY_CLIENT_ID : ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET : ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SITE_ADDRESS : ${{ secrets.SITE_ADDRESS }}
          NEXT_PUBLIC_MAPS_API_KEY : ${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
